apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: fortune-deploy
    group: pks-workshop
spec:
  type: ClusterIP
  ports:
    - port: 80
      # targetPort: 8080
      name: http
  selector:
    app: fortune-deploy-ui
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    group: pks-workshop
spec:
  type: ClusterIP
  ports:
    - port: 9080
      name: http
  selector:
    app: fortune-deploy-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: fortune-deploy-ui
    group: pks-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: azwickey/fortune-ui:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy-backend
  labels:
    app: fortune-deploy-backend
    group: pks-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortune-deploy-backend
  template:
    metadata:
      labels:
        app: fortune-deploy-backend
    spec:
      containers:
        - name: backend
          image: azwickey/fortune-backend-jee:latest
          env:
            - name: NODE_PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis-redis-ha.redis.svc.cluster.local"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /api/
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /api/
          #     port: http