kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdev-admin
subjects:
  - kind: User 
    name: appdev
    namespace: appdev
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io